import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, Check, ClipboardCopy, Download, FileText, Wrench } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router";
import { FIXTURES, http } from "@/api/client";
import { Button } from "@/components/button";
import { Card, Skeleton } from "@/components/card";
import { Tabs } from "@/components/popover-menu";
import { useReleases, versionLabel } from "@/lib/queries";
import { cn } from "@/lib/utils";
import goldenPlan from "./golden-plan.md?raw";
import { Prose } from "./Prose";

/* ---------------- data ---------------- */

const emptyPlan = (version: string) => `# Compliance fix plan: Wealthpilot ${versionLabel(version)}

> Generated by the AI Chief Compliance Officer · target: **coding agent** · AI pre-assessment, not legal advice

## Rules for the agent

1. There is nothing to fix in this release: no requirement is open.
2. Do not change code on behalf of this plan.

## How to verify

Re-run the assessment after any change to this release.
`;

async function fetchPlan(assessmentId: string, version: string): Promise<string> {
  if (FIXTURES) {
    await new Promise((r) => setTimeout(r, 60));
    return version === "0.9.0" ? goldenPlan : emptyPlan(version);
  }
  return http<string>(`/api/assessments/${assessmentId}/fix-plan.md`, { headers: { Accept: "text/markdown", "Content-Type": "text/plain" } });
}

/* ---------------- parsing ---------------- */

type Kind = "intro" | "rules" | "code" | "appendix" | "verify" | "other";
type Section = { kind: Kind; heading: string; body: string; text: string };

/** Splits the rendered plan at `## ` headings (outside code fences) and classifies each section. */
export function parsePlan(md: string): { title: string; sections: Section[] } {
  const lines = md.split("\n");
  const raw: string[][] = [[]];
  let fence = false;
  for (const l of lines) {
    if (/^```/.test(l)) fence = !fence;
    if (!fence && /^## /.test(l)) raw.push([]);
    raw[raw.length - 1].push(l);
  }
  const sections: Section[] = raw
    .map((chunk, i): Section => {
      const text = chunk.join("\n").trim();
      const heading = i === 0 ? (text.match(/^# (.*)$/m)?.[1] ?? "") : chunk[0].replace(/^## /, "").trim();
      const kind: Kind = i === 0 ? "intro"
        : /^rules/i.test(heading) ? "rules"
        : /^\d+\./.test(heading) ? "code"
        : /^appendix/i.test(heading) ? "appendix"
        : /^how to verify/i.test(heading) ? "verify" : "other";
      return { kind, heading, body: i === 0 ? text : chunk.slice(1).join("\n").trim(), text };
    })
    .filter((s) => s.text);
  return { title: sections[0]?.kind === "intro" ? sections[0].heading : "Fix plan", sections };
}

const joinMd = (s: Section[]) => s.map((x) => x.text).join("\n\n---\n\n");

/** What the coding agent receives: everything except the founder appendix. */
export function claudeCodePrompt(md: string): string {
  const { sections } = parsePlan(md);
  const plan = joinMd(sections.filter((s) => s.kind !== "appendix"));
  return [
    "You are a coding agent working in this repository. Implement the compliance fix plan below.",
    "Follow its rules exactly, work item by item, and stop and report if an item needs a file outside its boundaries.",
    "The founder appendix is not part of your task.",
    "",
    "---",
    "",
    plan,
    "",
  ].join("\n");
}

async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try { // clipboard API unavailable (insecure context, permissions): select-and-copy fallback
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.setAttribute("readonly", "");
      ta.style.cssText = "position:fixed;top:0;left:0;opacity:0;pointer-events:none";
      document.body.appendChild(ta);
      ta.select();
      const ok = document.execCommand("copy");
      document.body.removeChild(ta);
      return ok;
    } catch {
      return false;
    }
  }
}

/* ---------------- page ---------------- */

export function FixPlanPage() {
  const { release = "" } = useParams();
  const releases = useReleases();
  const rel = releases.data?.find((r) => r.release.id === release);
  const assessmentId = rel?.latest_assessment?.id;
  const version = rel?.release.version ?? "";

  const plan = useQuery({
    queryKey: ["fix-plan", release, assessmentId],
    queryFn: () => fetchPlan(assessmentId!, version),
    enabled: !!assessmentId,
    retry: false,
  });

  const parsed = useMemo(() => (plan.data ? parsePlan(plan.data) : null), [plan.data]);
  const [tab, setTab] = useState<"agent" | "founder">("agent");

  const loading = releases.isLoading || (!!assessmentId && plan.isLoading);
  const noAssessment = !!rel && !assessmentId;
  const missingRelease = !!releases.data && !rel;

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6" data-testid="fix-plan-page">
      <Link to={`/r/${release}/overview`} className="mb-4 inline-flex items-center gap-1 text-sm text-text-2 hover:text-text">
        <ArrowLeft className="h-3.5 w-3.5" /> Overview
      </Link>
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-xl"><Wrench className="h-5 w-5 text-text-2" /> Fix plan</h1>
          <p className="mt-1 text-sm text-text-2">
            Generated from the validated findings and the requirement templates{version ? <> for <span className="font-mono text-code">{versionLabel(version)}</span></> : null}. No LLM call, so the output is identical in the UI, CI and MCP.
          </p>
        </div>
        {plan.data && <Actions md={plan.data} version={version} />}
      </div>

      {loading && <PlanSkeleton />}

      {(releases.isError || missingRelease) && (
        <Notice title="Release not found" body="This release is not available. Pick another one from the switcher." />
      )}
      {noAssessment && (
        <Notice title="No assessment yet" body="Run an assessment on this release first; the fix plan is rendered from its findings." tone="neutral" />
      )}
      {plan.isError && (
        <Notice title="The fix plan could not be loaded" body="The plan for this assessment is not available yet. Try again in a moment." action={<Button onClick={() => plan.refetch()}>Retry</Button>} />
      )}

      {parsed && plan.data && (
        <Tabs.Root value={tab} onValueChange={(v) => setTab(v as typeof tab)}>
          <Tabs.List aria-label="Fix plan sections" className="mb-4 inline-flex h-9 items-center rounded-md border bg-surface-2 p-0.5">
            {([
              ["agent", "Code items", parsed.sections.filter((s) => s.kind === "code").length],
              ["founder", "Founder appendix", parsed.sections.filter((s) => s.kind === "appendix").length],
            ] as const).map(([v, label, n]) => (
              <Tabs.Trigger key={v} value={v} data-testid={`fixplan-tab-${v}`}
                className={cn("h-8 rounded-[6px] px-3 text-sm text-text-2 transition-colors duration-fast data-[state=active]:border data-[state=active]:bg-surface data-[state=active]:text-text data-[state=active]:shadow-sm")}>
                {label} {v === "agent" && <span className="tnum ml-1 text-text-3">{n}</span>}
              </Tabs.Trigger>
            ))}
          </Tabs.List>

          <Tabs.Content value="agent" className="space-y-4" data-testid="fixplan-agent">
            {parsed.sections.filter((s) => s.kind !== "appendix").map((s, i) => (
              <Card key={i} className="px-5 py-4" data-testid={s.kind === "code" ? "fixplan-item" : `fixplan-${s.kind}`}>
                <Prose>{s.text}</Prose>
              </Card>
            ))}
          </Tabs.Content>
          <Tabs.Content value="founder" className="space-y-4" data-testid="fixplan-founder">
            <p className="text-sm text-text-2">Documents and organisational actions for the founder. These are not part of the prompt copied for the coding agent.</p>
            {parsed.sections.filter((s) => s.kind === "appendix").map((s, i) => (
              <Card key={i} className="px-5 py-4"><Prose>{s.text}</Prose></Card>
            ))}
            {!parsed.sections.some((s) => s.kind === "appendix") && (
              <Card className="px-5 py-8 text-center text-sm text-text-2">No documents or organisational actions are open for this release.</Card>
            )}
          </Tabs.Content>
        </Tabs.Root>
      )}
    </div>
  );
}

function Actions({ md, version }: { md: string; version: string }) {
  const [copied, setCopied] = useState<"ok" | "fail" | null>(null);
  const timer = useRef<number>(0);
  const [href, setHref] = useState("");
  useEffect(() => {
    const u = URL.createObjectURL(new Blob([md], { type: "text/markdown" }));
    setHref(u);
    return () => URL.revokeObjectURL(u);
  }, [md]);
  const copy = async () => {
    const ok = await copyText(claudeCodePrompt(md));
    setCopied(ok ? "ok" : "fail");
    window.clearTimeout(timer.current);
    timer.current = window.setTimeout(() => setCopied(null), 2200);
  };
  return (
    <div className="flex flex-wrap items-center gap-2">
      <Button variant="primary" size="md" onClick={copy} data-testid="copy-prompt" aria-live="polite">
        {copied === "ok" ? <Check className="h-4 w-4" /> : <ClipboardCopy className="h-4 w-4" />}
        {copied === "ok" ? "Copied" : copied === "fail" ? "Copy failed, select the text" : "Copy as Claude Code prompt"}
      </Button>
      <Button asChild size="md">
        <a href={href} download={`fix-plan-${versionLabel(version || "plan")}.md`} data-testid="download-md"><Download className="h-4 w-4" /> Download .md</a>
      </Button>
    </div>
  );
}

function PlanSkeleton() {
  return (
    <div className="space-y-4" aria-busy="true" aria-label="Loading fix plan">
      <Skeleton className="h-28" /><Skeleton className="h-64" /><Skeleton className="h-48" />
    </div>
  );
}

export function Notice({ title, body, action, tone = "error" }: { title: string; body: string; action?: React.ReactNode; tone?: "error" | "neutral" }) {
  const Icon = tone === "error" ? AlertTriangle : FileText;
  return (
    <Card className="flex flex-col items-center gap-2 px-6 py-12 text-center" role={tone === "error" ? "alert" : "status"}>
      <Icon className={cn("h-6 w-6", tone === "error" ? "text-blocker-fg" : "text-text-3")} aria-hidden />
      <h2 className="text-base font-medium">{title}</h2>
      <p className="max-w-sm text-sm text-text-2">{body}</p>
      {action && <div className="mt-2">{action}</div>}
    </Card>
  );
}

export function register(): void {
  // The fix plan is a routed page; it contributes nothing to named slots.
}
