"""Deterministic fix plan (SPEC 6.11): pack templates + validated findings, no LLM, no timestamps."""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from .. import gate
from ..api import deps
from ..api.provisions import find_provision
from ..contracts import FindingView, Release, RemediationPart, Requirement
from ..models import ReleaseRow
from ..pack import load_pack

_SEV_ORDER = {"blocker": 0, "high": 1, "medium": 2, "low": 3}
_SEV_MARK = {"blocker": "🔴 blocker", "high": "🟠 high", "medium": "🟡 medium", "low": "⚪ low"}
_CLOSED = ("satisfied", "not_applicable")

RULES = [
    "Fix only the items below, in order. Each item lists the files you may touch. Stop and report if a fix needs any other file.",
    "Keep behaviour that no item mentions unchanged. Don't add dependencies.",
    "Add or update tests for every `done_when` you can check automatically.",
    "Work on a fix branch. Commit once per item: `fix(compliance): <requirement id> <short title>`. The release PR runs the CCO compliance check.",
    "The appendix items are for the founder, not for you. Code items that depend on them say so.",
    "When you're done, the CCO re-assesses the new release. Every item's last `done_when` is checked there.",
]


def _tag(v: FindingView, req: Requirement) -> str:
    c = v.effective_conclusion
    if c == "potential_violation":
        return _SEV_MARK[req.severity]
    if c == "insufficient_evidence":
        return "🔵 missing mandatory evidence" if req.mandatory else "🔵 insufficient evidence"
    return "◌ uncertain"


def _legal_basis(v: FindingView) -> str:
    out = []
    for c in v.citations:
        p = find_provision(c)
        if p is None:
            out.append(c)
            continue
        art = f"Art. {p.article}" + (f"({p.paragraph})" if p.paragraph else "")
        out.append(f"{p.act_title} {art}")
    return " · ".join(out)


def _gate_line(readiness) -> str:
    c = readiness.counts
    bits = [
        (c.blockers, "blocker" + ("s" if c.blockers != 1 else "")),
        (c.missing_evidence, "missing mandatory evidence"),
        (c.high, "high"),
        (c.medium, "medium"),
        (c.low, "low"),
    ]
    detail = ", ".join(f"{n} {t}" for n, t in bits if n)
    return f"**{readiness.gate_label.upper()}**" + (f" ({detail})" if detail else "")


def _bullets(items: list[str], pre: str = "- ") -> list[str]:
    return [f"{pre}{i}" for i in items]


def render_fix_plan(s: Session, assessment_id: str) -> str:
    assessment = deps.get_assessment(s, assessment_id)
    release: Release = deps.get_release(s, assessment.release_id)
    product, profile = deps.get_product(s)
    views = deps.assessment_views(s, assessment)
    pack_reqs = {r.id: r for r in load_pack().requirements}
    readiness = gate.compute_readiness(release, assessment, views, deps.load_requirements(s), None)

    # (severity rank, requirement order, part) for every part of every open requirement
    open_items: list[tuple[FindingView, Requirement, RemediationPart]] = []
    for v in views:
        req = pack_reqs.get(v.requirement_id)
        if req is None or v.effective_conclusion in _CLOSED:
            continue
        open_items += [(v, req, p) for p in req.remediation.parts]
    open_ids = {p.id for _, _, p in open_items}
    open_items.sort(key=lambda t: (_SEV_ORDER[t[1].severity], t[2].id))
    code = [t for t in open_items if t[2].kind == "code"]
    appendix = sorted((t for t in open_items if t[2].kind != "code"), key=lambda t: t[2].id)
    multi = {rid for rid in {t[1].id for t in open_items} if sum(1 for t in open_items if t[1].id == rid and t[2].kind == "code") > 0
             and sum(1 for t in open_items if t[1].id == rid) > 1}

    L: list[str] = [
        f"# Compliance fix plan: {product.name} v{release.version}",
        "",
        "> Generated by the AI Chief Compliance Officer · target: **coding agent**",
        f"> Product: {product.name} ({product.description}) · Jurisdictions: {', '.join(profile.jurisdictions)}",
        f"> Release assessed: v{release.version}" + (f" = `{release.git_sha}`" if release.git_sha else "")
        + f" · Gate: {_gate_line(readiness)} · {' · '.join(readiness.labels)}",
        "",
        "## Rules for the agent",
        "",
    ]
    L += [f"{i}. {r}" for i, r in enumerate(RULES, 1)]
    L += ["", "---", ""]

    num = {}
    for n, (_, _, p) in enumerate(code, 1):
        num[p.id] = n
    for v, req, p in code:
        suffix = " (code part)" if req.id in multi else ""
        L.append(f"## {num[p.id]}. {req.id}{suffix}: {req.title} · {_SEV_MARK[req.severity]}")
        L.append("")
        basis = _legal_basis(v)
        if basis:
            L.append(f"**Legal basis:** {basis}")
        deps_open = [d for d in p.depends_on if d in open_ids]
        if deps_open:
            L.append(f"**Depends on:** appendix {', '.join(deps_open)}. Do this item once the founder has completed it.")
        L.append(f"**Problem:** {v.reasoning_summary}")
        L += ["", "**Locations**", *_bullets([f"`{x}`" for x in p.locations]), ""]
        L += ["**Required change**", "", p.required_change.strip(), ""]
        L.append("**Boundaries:** " + (", ".join(f"`{b}`" for b in p.boundaries) or "none"))
        L += ["", "**Done when**", *_bullets(p.done_when, "- [ ] "), ""]

    if appendix:
        L += ["---", "", "## Appendix: documents and organisational actions (founder, not the coding agent)", "",
              "| # | Requirement | Action | Evidence the CCO will look for |", "|---|---|---|---|"]
        seen: set[str] = set()
        for v, req, p in appendix:
            tag = f" · {_tag(v, req)}" if req.id not in seen else ""
            seen.add(req.id)
            L.append(f"| {p.id} | {req.id}{tag} | {p.required_change.strip()} | {' '.join(p.done_when) or ' '} |")
        L.append("")

    L += ["## How to verify", "",
          f"Create the next release in the CCO from the fix branch, attach the appendix documents ({', '.join(p.id for _, _, p in appendix) or 'none'}), "
          "and run the assessment (or call MCP `get_release_readiness`). Expected result: **READY**, with every item above satisfied.", ""]
    return "\n".join(L).replace("\n\n\n", "\n\n")


def resolve_release(s: Session, version: str | None) -> Release:
    """Release by version, else the newest release that has a completed assessment."""
    if version:
        row = s.scalars(select(ReleaseRow).where(ReleaseRow.version == version.lstrip("v"))).first()
        if row is None:
            raise ValueError(f"release version {version!r} not found")
        return Release.model_validate(row.data)
    for r in deps.list_releases(s):
        if deps.latest_assessment(s, r.id, completed_only=True) is not None:
            return r
    raise ValueError("no release with a completed assessment")


def render_fix_plan_for_version(s: Session, version: str | None) -> str:
    rel = resolve_release(s, version)
    a = deps.latest_assessment(s, rel.id, completed_only=True)
    if a is None:
        raise ValueError(f"release {rel.version!r} has no completed assessment")
    return render_fix_plan(s, a.id)
