/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/_contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contracts Schema
         * @description Not a real endpoint: exposes AgentEvent, SseEnvelope and FindingCandidate in OpenAPI.
         */
        get: operations["contracts_schema_api__contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_api_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_assessments__assessment_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/fix-plan.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fix Plan */
        get: operations["fix_plan_api_assessments__assessment_id__fix_plan_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Finding */
        get: operations["get_finding_api_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review */
        post: operations["create_review_api_findings__finding_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_product_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Profile */
        put: operations["put_profile_api_product_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provisions/{provision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provision */
        get: operations["get_provision_api_provisions__provision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provisions/{provision_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Related Provisions */
        get: operations["related_provisions_api_provisions__provision_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Releases */
        get: operations["list_releases_api_releases_get"];
        put?: never;
        /** Create Release */
        post: operations["create_release_api_releases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Release */
        post: operations["import_release_api_releases_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Release */
        get: operations["get_release_api_releases__release_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/{release_id}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Assessment */
        post: operations["start_assessment_api_releases__release_id__assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/{release_id}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readiness */
        get: operations["get_readiness_api_releases__release_id__readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Review */
        post: operations["revoke_review_api_reviews__review_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description text/event-stream of SseEnvelope frames. Query: requirement_id, after_seq.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentEvent */
        AgentEvent: {
            /** Attempt */
            attempt?: number | null;
            /** Error */
            error?: string | null;
            /** Input Preview */
            input_preview?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Output Preview */
            output_preview?: string | null;
            /** Requirement Id */
            requirement_id?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Run Kind
             * @default assessment
             * @enum {string}
             */
            run_kind: "assessment" | "mcp";
            /** Seq */
            seq: number;
            /** Summary */
            summary: string;
            /** Tokens */
            tokens?: number | null;
            /** Tool */
            tool?: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Type
             * @enum {string}
             */
            type: "step" | "scope" | "model_request" | "model_response" | "tool_call" | "tool_result" | "retry" | "finding" | "gate" | "run_end";
        };
        /** Artifact */
        Artifact: {
            /** Files */
            files?: components["schemas"]["CodeFile"][];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "business_plan" | "product_spec" | "privacy_policy" | "terms" | "regulatory_registration" | "code_repo" | "other";
            /** Path */
            path: string;
            /** Release Id */
            release_id: string;
            /** Sha256 */
            sha256: string;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** Assessment */
        Assessment: {
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Pack Version */
            pack_version: string;
            /** Release Id */
            release_id: string;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
        };
        /** AssessmentCreated */
        AssessmentCreated: {
            /** Assessment Id */
            assessment_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** Body_create_release_api_releases_post */
        Body_create_release_api_releases_post: {
            /** Bundle */
            bundle: string;
            /** Version */
            version: string;
        };
        /** ChangesSinceVersion */
        ChangesSinceVersion: {
            /** New */
            new?: string[];
            /** Resolved */
            resolved?: string[];
            /** Unchanged */
            unchanged?: string[];
        };
        /**
         * CiResult
         * @description `result.json` written by `cco audit`, consumed by `cco import`.
         */
        CiResult: {
            assessment: components["schemas"]["Assessment"];
            /** Comment Md */
            comment_md?: string | null;
            /** Error */
            error?: string | null;
            /** Events */
            events?: components["schemas"]["AgentEvent"][];
            /** Exit Code */
            exit_code: number;
            /** Findings */
            findings: components["schemas"]["FindingView"][];
            /**
             * Format Version
             * @default 1
             */
            format_version: number;
            readiness: components["schemas"]["Readiness"];
            release: components["schemas"]["Release"];
            /** Reviews */
            reviews?: components["schemas"]["Review"][];
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "engine_error";
        };
        /** CodeFile */
        CodeFile: {
            /** Content */
            content: string;
            /** Path */
            path: string;
        };
        /** CodeRef */
        CodeRef: {
            /** Artifact Id */
            artifact_id: string;
            /** End Line */
            end_line: number;
            /** Path */
            path: string;
            /** Quote */
            quote: string;
            /** Start Line */
            start_line: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
        };
        /** Confidence */
        Confidence: {
            /** Applicability */
            applicability: number;
            /** Evidence */
            evidence: number;
            /** Finding */
            finding: number;
        };
        /** CounselReviewed */
        CounselReviewed: {
            /** Reviewed */
            reviewed: number;
            /** Total */
            total: number;
        };
        /** DocumentSpanRef */
        DocumentSpanRef: {
            /** Artifact Id */
            artifact_id: string;
            /** End */
            end?: number | null;
            /** Quote */
            quote: string;
            /** Start */
            start?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document_span";
        };
        /** DomainCoverage */
        DomainCoverage: {
            /** Domain */
            domain: string;
            /**
             * Insufficient Evidence
             * @default 0
             */
            insufficient_evidence: number;
            /**
             * Not Applicable
             * @default 0
             */
            not_applicable: number;
            /**
             * Potential Violation
             * @default 0
             */
            potential_violation: number;
            /**
             * Satisfied
             * @default 0
             */
            satisfied: number;
            /** Total */
            total: number;
            /**
             * Uncertain
             * @default 0
             */
            uncertain: number;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** EvidenceHints */
        EvidenceHints: {
            /** Artifact Kinds */
            artifact_kinds?: ("business_plan" | "product_spec" | "privacy_policy" | "terms" | "regulatory_registration" | "code_repo" | "other")[];
            /** Code Globs */
            code_globs?: string[];
        };
        /** FindingCandidate */
        FindingCandidate: {
            /** Citations */
            citations?: string[];
            /**
             * Conclusion
             * @enum {string}
             */
            conclusion: "satisfied" | "potential_violation" | "insufficient_evidence" | "not_applicable" | "uncertain";
            confidence: components["schemas"]["Confidence"];
            /** Evidence */
            evidence?: (components["schemas"]["DocumentSpanRef"] | components["schemas"]["CodeRef"] | components["schemas"]["MissingRef"])[];
            /** Reasoning Summary */
            reasoning_summary: string;
            /** Requirement Id */
            requirement_id: string;
            /** Title */
            title: string;
        };
        /** FindingDetail */
        FindingDetail: {
            finding: components["schemas"]["FindingView"];
            /** Provisions */
            provisions?: components["schemas"]["LegalProvision"][];
            requirement: components["schemas"]["Requirement"];
            /** Reviews */
            reviews?: components["schemas"]["Review"][];
        };
        /**
         * FindingView
         * @description A finding as served by the API: AI value plus the applicable review, if any.
         */
        FindingView: {
            applicable_review?: components["schemas"]["Review"] | null;
            /** Assessment Id */
            assessment_id: string;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /** Carried From Version */
            carried_from_version?: string | null;
            /** Citations */
            citations?: string[];
            /**
             * Conclusion
             * @enum {string}
             */
            conclusion: "satisfied" | "potential_violation" | "insufficient_evidence" | "not_applicable" | "uncertain";
            confidence: components["schemas"]["Confidence"];
            /**
             * Effective Conclusion
             * @enum {string}
             */
            effective_conclusion: "satisfied" | "potential_violation" | "insufficient_evidence" | "not_applicable" | "uncertain";
            /** Evidence */
            evidence?: (components["schemas"]["DocumentSpanRef"] | components["schemas"]["CodeRef"] | components["schemas"]["MissingRef"])[];
            /** Evidence Fingerprint */
            evidence_fingerprint: string;
            /** Id */
            id: string;
            /** Reasoning Summary */
            reasoning_summary: string;
            /** Requirement Id */
            requirement_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocker" | "high" | "medium" | "low";
            /** Title */
            title: string;
            /** Validation Notes */
            validation_notes?: string[];
        };
        /** GateCounts */
        GateCounts: {
            /**
             * Blockers
             * @default 0
             */
            blockers: number;
            /**
             * High
             * @default 0
             */
            high: number;
            /**
             * Low
             * @default 0
             */
            low: number;
            /**
             * Medium
             * @default 0
             */
            medium: number;
            /**
             * Missing Evidence
             * @default 0
             */
            missing_evidence: number;
            /**
             * Requirements Evaluated
             * @default 0
             */
            requirements_evaluated: number;
            /**
             * Requirements Total
             * @default 0
             */
            requirements_total: number;
            /**
             * Uncertain Unreviewed
             * @default 0
             */
            uncertain_unreviewed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            result: components["schemas"]["CiResult"];
        };
        /** LegalProvision */
        LegalProvision: {
            /** Act Title */
            act_title: string;
            /** Article */
            article: string;
            /** Celex */
            celex?: string | null;
            /** Embedding */
            embedding?: number[] | null;
            /** Id */
            id: string;
            /** Issuer */
            issuer?: string | null;
            /** Jurisdiction */
            jurisdiction: string;
            /**
             * Kind
             * @default law
             * @enum {string}
             */
            kind: "law" | "guidance";
            /** Legi Id */
            legi_id?: string | null;
            /** Paragraph */
            paragraph?: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Source
             * @enum {string}
             */
            source: "cellar" | "legifrance" | "manual";
            /** Source Url */
            source_url: string;
            /** Text */
            text: string;
        };
        /** MissingRef */
        MissingRef: {
            /**
             * Artifact Kind
             * @enum {string}
             */
            artifact_kind: "business_plan" | "product_spec" | "privacy_policy" | "terms" | "regulatory_registration" | "code_repo" | "other";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "missing";
        };
        /** Product */
        Product: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string;
        };
        /** ProductOut */
        ProductOut: {
            product: components["schemas"]["Product"];
            profile: components["schemas"]["RegulatoryProfile"];
        };
        /** Readiness */
        Readiness: {
            /** Assessment Id */
            assessment_id: string;
            /** Blockers */
            blockers?: string[];
            changes_since_previous?: components["schemas"]["ChangesSinceVersion"];
            counsel_reviewed: components["schemas"]["CounselReviewed"];
            counts: components["schemas"]["GateCounts"];
            /** Coverage */
            coverage: components["schemas"]["DomainCoverage"][];
            /**
             * Gate
             * @enum {string}
             */
            gate: "NOT_READY" | "REVIEW_REQUIRED" | "READY";
            /** Gate Label */
            gate_label: string;
            /** Labels */
            labels: string[];
            /** Previous Release Id */
            previous_release_id?: string | null;
            /** Release Id */
            release_id: string;
            /** Version */
            version: string;
        };
        /** RegulatoryProfile */
        RegulatoryProfile: {
            /** Activities */
            activities: string[];
            /** Ai Uses */
            ai_uses: string[];
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Customer Types */
            customer_types: string[];
            /** Data Categories */
            data_categories: string[];
            /** Industry */
            industry: string;
            /** Jurisdictions */
            jurisdictions: string[];
            /** Stage */
            stage: string;
        };
        /** Release */
        Release: {
            /** Branch */
            branch?: string | null;
            /** Ci Run Url */
            ci_run_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Id */
            id: string;
            /** Pr Number */
            pr_number?: number | null;
            /** Previous Release Id */
            previous_release_id?: string | null;
            /**
             * Product Id
             * @default wealthpilot
             */
            product_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "seed" | "ui" | "ci";
            /** Version */
            version: string;
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            latest_assessment?: components["schemas"]["Assessment"] | null;
            release: components["schemas"]["Release"];
        };
        /** Remediation */
        Remediation: {
            /** Parts */
            parts?: components["schemas"]["RemediationPart"][];
        };
        /** RemediationPart */
        RemediationPart: {
            /** Boundaries */
            boundaries?: string[];
            /** Depends On */
            depends_on?: string[];
            /** Done When */
            done_when?: string[];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "code" | "document" | "organisational";
            /** Locations */
            locations?: string[];
            /** Required Change */
            required_change: string;
            /** Title */
            title: string;
        };
        /** Requirement */
        Requirement: {
            /** Alias */
            alias?: string | null;
            /** Applies When */
            applies_when: string;
            /** Derived From */
            derived_from: string[];
            /** Domain */
            domain: string;
            evidence_hints: components["schemas"]["EvidenceHints"];
            /** Evidence Needed */
            evidence_needed: string;
            /** Id */
            id: string;
            /**
             * Mandatory
             * @default false
             */
            mandatory: boolean;
            remediation?: components["schemas"]["Remediation"];
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocker" | "high" | "medium" | "low";
            /** Statement */
            statement: string;
            /** Title */
            title: string;
        };
        /** Review */
        Review: {
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "override" | "not_applicable" | "need_evidence";
            /** Evidence Fingerprint */
            evidence_fingerprint: string;
            /** Finding Id */
            finding_id: string;
            /** Id */
            id: string;
            /** Override Conclusion */
            override_conclusion?: ("satisfied" | "potential_violation" | "insufficient_evidence" | "not_applicable" | "uncertain") | null;
            /** Product Id */
            product_id: string;
            /** Requirement Id */
            requirement_id: string;
            /** Reviewer Name */
            reviewer_name: string;
            /** Revoked At */
            revoked_at?: string | null;
        };
        /** ReviewCreate */
        ReviewCreate: {
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "override" | "not_applicable" | "need_evidence";
            /** Override Conclusion */
            override_conclusion?: ("satisfied" | "potential_violation" | "insufficient_evidence" | "not_applicable" | "uncertain") | null;
            /** Reviewer Name */
            reviewer_name: string;
        };
        /**
         * SchemaBundle
         * @description Only exists so OpenAPI exposes the non-REST contracts (SSE frame, agent output) as types.
         */
        SchemaBundle: {
            candidate: components["schemas"]["FindingCandidate"];
            event: components["schemas"]["AgentEvent"];
            /** Generated At */
            generated_at?: string | null;
            sse: components["schemas"]["SseEnvelope"];
        };
        /**
         * SseEnvelope
         * @description One SSE frame: `id: <seq>`, `event: agent_event`, `data: <AgentEvent json>`.
         */
        SseEnvelope: {
            data: components["schemas"]["AgentEvent"];
            /**
             * Event
             * @default agent_event
             * @constant
             */
            event: "agent_event";
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contracts_schema_api__contracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaBundle"];
                };
            };
        };
    };
    get_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_api_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_assessments__assessment_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fix_plan_api_assessments__assessment_id__fix_plan_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finding_api_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_findings__finding_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_product_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
        };
    };
    put_profile_api_product_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegulatoryProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provision_api_provisions__provision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalProvision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_provisions_api_provisions__provision_id__related_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalProvision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_releases_api_releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"][];
                };
            };
        };
    };
    create_release_api_releases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_release_api_releases_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_release_api_releases_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_release_api_releases__release_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_assessment_api_releases__release_id__assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentCreated"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_readiness_api_releases__release_id__readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_review_api_reviews__review_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                requirement_id?: string | null;
                after_seq?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
